# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# To use pre-commit install the "pre-commit" python package, which should be listed in the "requirements-dev.txt" file.
# Then run the "pre-commit install" command.
#
# To update pre-commit hooks use "pre-commit autoupdate"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files # prevents giant files from being committed.
    -   id: check-json # checks json files for parseable syntax.
    -   id: check-symlinks # checks for symlinks which do not point to anything.
    -   id: check-toml # checks toml files for parseable syntax.
    -   id: check-xml # checks xml files for parseable syntax.
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: trailing-whitespace # trims trailing whitespace.
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.0b1
    hooks:
      - id: pylint
        types: [python]
        args: ["-d C0116,C0115,C0114,E0611,E1101,R0903,W0703,W0707,W0123,E0401", "-j 2"]
        exclude: (test_|_test)
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: tests.sh
        language: script
        types: [python]
        always_run: true